steps:
  - id: "Build do source em Go"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['install', 'soma']
    env: ['PROJECT_ROOT=soma']

  - id: "Teste do compilado"
    name: 'gcr.io/cloud-builders/go:alpine'
    args: ['test', 'soma']
    env: ['PROJECT_ROOT=soma']

  - id: "Publicacao da imagem no registry pessoal"
    name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/go-soma', '.']

images: ['gcr.io/$PROJECT_ID/go-soma:latest']
